apiVersion: v1
kind: Namespace
metadata:
  name: redis
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: redis
spec:
  selector:
    app: redis
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:alpine
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: redis
data:
  REDIS_HOST: redis-service
  REDIS_PORT: "6379"
---
# To clear the cache every 2 minutes, should be enough for this demo
apiVersion: batch/v1
kind: CronJob
metadata:
  name: redis-clear-cache
  namespace: redis
spec:
  schedule: "*/2 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: redis-clear-cache
              image: redis:alpine
              command: ["redis-cli", "-h", "$(REDIS_HOST)", "-p", "$(REDIS_PORT)", "FLUSHALL"]
              envFrom:
                - configMapRef:
                    name: redis-config
              imagePullPolicy: IfNotPresent
          restartPolicy: Never